export const cards = [
  { queueNumber: 1, orderId: "#6836456", name: "Attipoe Bolati", items: 4, timeSpent: "6 min ago", table: "2", status: "Ready...", emoji: "😀" },
  { queueNumber: 2, orderId: "#5729384", name: "Jane Smith", items: 2, timeSpent: "10 min ago", table: " 3", status: "Ready...", emoji: "🍕" },
  { queueNumber: 3, orderId: "#2394827", name: "Mark Johnson", items: 5, timeSpent: "12 min ago", table: "1", status: "Ready...", emoji: "🚀" },
  { queueNumber: 4, orderId: "#3847563", name: "Emily Davis", items: 3, timeSpent: "15 min ago", table: "4", status: "Ready...", emoji: "🔥" },
  { queueNumber: 5, orderId: "#7384921", name: "Michael Brown", items: 4, timeSpent: "20 min ago", table: "1", status: "On Process", emoji: "🌟" },
  { queueNumber: 6, orderId: "#1928374", name: "Sarah Wilson", items: 6, timeSpent: "25 min ago", table: "3", status: "On Process", emoji: "🎉" },
  { queueNumber: 7, orderId: "#8394726", name: "Chris Lee", items: 2, timeSpent: "30 min ago", table: " 2", status: "On Process", emoji: "🕒" },
  { queueNumber: 8, orderId: "#3847564", name: "Patricia Martinez", items: 3, timeSpent: "35 min ago", table: "1", status: "On Process", emoji: "📚" },
  { queueNumber: 9, orderId: "#1837265", name: "David Harris", items: 7, timeSpent: "40 min ago", table: " 3", status: "Pending", emoji: "🎨" },
  { queueNumber: 10, orderId: "#7283645", name: "Laura Clark", items: 1, timeSpent: "45 min ago", table: " 1", status: "Pending", emoji: "🌍" },
  { queueNumber: 11, orderId: "#9183746", name: "Anna Miller", items: 2, timeSpent: "50 min ago", table: " 2", status: "Pending", emoji: "🚴" },
  { queueNumber: 12, orderId: "#8273645", name: "Robert Wilson", items: 3, timeSpent: "55 min ago", table: "1", status: "Pending", emoji: "🎵" },
  { queueNumber: 13, orderId: "#6472819", name: "Karen Taylor", items: 4, timeSpent: "60 min ago", table: "1", status: "Pending", emoji: "🎤" },
  { queueNumber: 14, orderId: "#8172639", name: "Thomas Anderson", items: 5, timeSpent: "65 min ago", table: "2", status: "Pending", emoji: "📷" },
  { queueNumber: 15, orderId: "#7263849", name: "Nina Parker", items: 3, timeSpent: "70 min ago", table: "4", status: "Pending", emoji: "🎈" },
  { queueNumber: 16, orderId: "#9182736", name: "Samuel Roberts", items: 2, timeSpent: "75 min ago", table: "1", status: "Pending", emoji: "🎲" },
  { queueNumber: 17, orderId: "#8273649", name: "Isabella Lopez", items: 1, timeSpent: "80 min ago", table: "3", status: "Pending", emoji: "🎭" },
  { queueNumber: 18, orderId: "#1837268", name: "James Hall", items: 4, timeSpent: "85 min ago", table: "1", status: "Pending", emoji: "🍹" },
  { queueNumber: 19, orderId: "#7384952", name: "Elizabeth King", items: 5, timeSpent: "90 min ago", table: "6", status: "Pending", emoji: "🎧" },
  { queueNumber: 20, orderId: "#9182749", name: "Alexander Young", items: 6, timeSpent: "95 min ago", table: " 2", status: "Pending", emoji: "🎯" },
];

export const completedOrders = [  
  { orderId: "#5184879", timeSpent: "5 mins", status: "completed" },
  { orderId: "#4589562", timeSpent: "8 mins", status: "completed" },
  { orderId: "#4885622", timeSpent: "16 mins", status: "completed" },
  { orderId: "#4578623", timeSpent: "22 mins", status: "completed" },
  { orderId: "#6482930", timeSpent: "12 mins", status: "completed" },
  { orderId: "#9283745", timeSpent: "18 mins", status: "completed" },
  { orderId: "#7384926", timeSpent: "20 mins", status: "completed" },
  { orderId: "#6273845", timeSpent: "25 mins", status: "completed" },
  { orderId: "#1827364", timeSpent: "28 mins", status: "completed" },
  { orderId: "#2837465", timeSpent: "30 mins", status: "completed" },
  { orderId: "#3847567", timeSpent: "35 mins", status: "completed" },
  { orderId: "#4758678", timeSpent: "40 mins", status: "completed" },
  { orderId: "#5869789", timeSpent: "45 mins", status: "completed" },
];
